[package]
name = "nanotricks"
version = "0.1.0"
author = [ "nanocryk" ]
description = "Collection of tools to write cleaner and shorter code"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nanocryk/nanotricks"

[dependencies]
similar-asserts = { version = "1.5.0", optional = true }