[package]
name = "nanotweaks"
version = "0.2.0"
authors = [ "nanocryk" ]
description = "Collection of tools to write cleaner and shorter code"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/nanocryk/nanotweaks"

[dependencies]
paste = "1.0.14"
similar-asserts = { version = "1.5.0", optional = true }
